apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager-lego-webhook
    repo:  https://yxwuxuanl.github.io/cert-manager-lego-webhook
    version: 1.2.0
    releaseName: cert-manager-lego-webhook
    namespace: tooling
    valuesFile: values.yaml