aksbyocni:
  enabled: true
azure:
  resourceGroup: rg-aks-cluster2
cluster:
  id: 2
  name: aks-cluster2
clustermesh:
  apiserver:
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      type: LoadBalancer
    tls:
      auto:
        enabled: true
        method: cronJob
        schedule: 0 0 1 */4 *
  config:
    clusters:
      - ips:
          - 192.168.1.133
        name: aks-cluster1
        port: 2379
        tls:
          caCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGRENDQWZ5Z0F3SUJBZ0lSQUljY1g1NUp4Q0h3TC9qc05pN2hlVHd3RFFZSktvWklodmNOQVFFTEJRQXcKRkRFU01CQUdBMVVFQXhNSlEybHNhWFZ0SUVOQk1CNFhEVEkxTURFeU1qRTFNVFkxT0ZvWERUSTRNREV5TWpFMQpNVFkxT0Zvd0ZERVNNQkFHQTFVRUF4TUpRMmxzYVhWdElFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUF0WUJvME94a2FCdVpIczBPdmlDZjBBVHNyTDZobnVUcTVFak1hUVlYdkpEU1J4OXIKcTZkUktiUWlvV1huWGk5WjQ1TmJGM1c3VXgyd0hZQzliVGl0WlAzaXp1SDFqeElCUlFUYlZyY0hXNVMwSzhFLwpWTlJOYW4wRTNxQ0daSVhrUloySEZiMWkrMzJJcHZiMCtSeENoSTNZd3kzVXcyN0lHS1ZpVktHTERyWUQvZUdvCnRCT0RDUnpjWDlETmRRaHdlTWpnTFJ3Rmw4aGpOOEVmUXMraWVrcGJ4SlVKNGtnMC9mS2MwVTdoTHZiblNwc3YKTnp5eG5HYjBzbzFZVnBNRFdRc1lyK3VJWld1RHVRWlVlWG16ekRMWWRLQlFsTVZVeXlOSXdsUnptOG0zeVJmSgpMVFNsV2Z3dlRwVS9EOG1FTXRmU2ZFZ1FwSlhHN3hVaHViNTZ0UUlEQVFBQm8yRXdYekFPQmdOVkhROEJBZjhFCkJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdIUVlEVlIwT0JCWUVGRU54V2NuRVJtc0lSVUNjZ081cjBWNDByV3VMTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQiswNVZSV1BFalcvSkpQQXRPTTJFMkJlMXhpOVVMbnZVaDdVNEwybEZvKys5Z0pybEkyaXNDCm9Ga3FBOWxBbmpUeE5ZTHM5YXptQm90Q08yN05tZ0dyb09pYmc0Vlh3Nk5FUzVMeWxKWjBXQWkvZ0NkN0xnRHoKbFNrVlcvbUtWWkpjVC92RitjOUlTTzFqRk84cGtxMkljeG8yZUtyS3B6TkRWSlJIcGcvSUlYZThzOXR4amRSYwpCUW41K1ptK29XNEl0UjArb3duek9lVUtKOGRMc2xmb044R2M4Smc3NDhHVkUxdFhCczMwMG5BWWxWclk2K3JzCkNjbjFWOC9RaWNBMzQvRnBHWDZuUEo3VkVJSkV5SUJ3QjRrakpvN3NZK2lmaUZ6d3A3WjhpRnc3RWNJai9JN3oKYW9nemw3djAyYUJDY3ZtM1Avek5yZWhXVXJNUmFmcVUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
          cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNYVENDQVVXZ0F3SUJBZ0lVV3Bta3lwQnBqWEZ1QTlZOXlYNVZ3cmpzaHBNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF4TUpRMmxzYVhWdElFTkJNQjRYRFRJMU1ERXlNakUxTWpVd01Gb1hEVEk0TURFeQpNakUxTWpVd01Gb3dFVEVQTUEwR0ExVUVBeE1HY21WdGIzUmxNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFdDlLNHdiclQyU2xWcXZtS1ZYdEN2UWFFMWd0U0lwYS90Y1BwSkl2MjJRbXBCcGlyZ1V3ZmU3NnAKb1pXMUQ3QjlhOVk0UFF4YXVQU2pPdTd5cGpWeklhTjFNSE13RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZApKUVFNTUFvR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRk9ybnZrd29zM2VGClRYcmN5Wm80VUhtM3o2MlJNQjhHQTFVZEl3UVlNQmFBRkVOeFdjbkVSbXNJUlVDY2dPNXIwVjQwcld1TE1BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUN6aDJLNURNNnFMUEU1Rm5NZE13SlY3cEFFNStaWCtzem5rd0h5MVRhQgoyT2ZZYmlSR1JZbTdXY0hrZ0wwbVdwUVp5cEg0QzRyNTZIWnE2S242Z0NRMkM2dHhPR21waW5nV0tkNEZVUnlWClZRMi9ZTkYwNzdvc3NGOENNeFN5OU5uMlZROTRaeVRvRy93L0NTbkZ6UGJVWmFRM2tFN1JEWUNNdkxwOWpjQkYKRWhoZThBVFpQS2p4OXhxWk1KYXMvKzZkRG1zK1Y1c3ZGNTVxMW1GUWZkMkt1NXVJdGJXOElPNVBIMXpzRDJTRgptQUhKN2lJTE1zOXhkeGgyUmZNWE0vTXUrcWwvUjVIK1M5ekQrUmRER3hYUkVGNGI0SzFqUnE5Z2dSUVBUNVY5ClZqQWJOa3N6TExWdU1QREpXMllaOGxQZlhBNmVETGgrdVN2VU4vc3JBTENWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhoektnQTFkaENxZ1Rnc295S0tDbVdsYjY3dWZUQzRaTmhZd1RZUnJiN2RvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdDlLNHdiclQyU2xWcXZtS1ZYdEN2UWFFMWd0U0lwYS90Y1BwSkl2MjJRbXBCcGlyZ1V3ZgplNzZwb1pXMUQ3QjlhOVk0UFF4YXVQU2pPdTd5cGpWeklRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    enabled: true
  useAPIServer: true
externalWorkloads:
  enabled: false
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.3.0.0/16
ipv4NativeRoutingCIDR: 10.0.0.0/8
nodeinit:
  enabled: true
operator:
  replicas: 1
