aksbyocni:
  enabled: true
azure:
  resourceGroup: rg-aks-cluster2
cluster:
  id: 2
  name: aks-cluster2
clustermesh:
  apiserver:
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      type: LoadBalancer
    tls:
      auto:
        enabled: true
        method: cronJob
        schedule: 0 0 1 */4 *
  useAPIServer: true
externalWorkloads:
  enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.3.0.0/16
ipv4NativeRoutingCIDR: 10.0.0.0/8
nodeinit:
  enabled: true
operator:
  replicas: 1
