apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/Azure/azure-service-operator/releases/download/v2.12.0/azureserviceoperator_v2.12.0.yaml
- secret.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --crd-pattern=resources.azure.com/*;containerservice.azure.com/*;network.azure.com/*;compute.azure.com/*
      - path: "/spec/replicas"
        op: add
        value: 1 
    target:
      kind: Deployment