apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.crds.yaml

helmCharts:
  - name: cert-manager
    repo:  https://charts.jetstack.io
    version: 1.17.1
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml