apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kyverno
    repo:  https://kyverno.github.io/kyverno/
    version: v1.13.4
    releaseName: kyverno
    namespace: kyverno