apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coroot.yaml

helmCharts:
  - name: coroot-operator
    repo:  https://coroot.github.io/helm-charts
    version: 0.3.0
    releaseName: coroot-operator
    namespace: coroot
    valuesFile: values.yaml