apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: paperless-ngx
    version: 0.24.1
    repo: https://charts.gabe565.com
    namespace: apps
    releaseName: paperless-ngx
