apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cattle-system

helmCharts:
  - name: rancher
    repo: https://releases.rancher.com/server-charts/latest
    version: "2.10.3"
    releaseName: rancher
    namespace: cattle-system
