apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: alloy
    repo:  https://grafana.github.io/helm-charts
    version: 1.1.0
    releaseName: alloy
    namespace: tooling
    valuesFile: values.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GRAFANA_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: grafana-api-token
              key: password
    target:
      kind: DaemonSet